### ISSUE TITLE
Price Oracles don't update

### ISSUE THREAD

**Issue by raymonddurk** [MyCryptoHQ/MyCrypto-Beta#23]
It is showing a balance of ETH, DAI, etc. but all at a $0.00 value. If you click view details, the Eth value shows but nothing else. It then obviously impacts the 100% of the funds value.

![MyCrypto Beta](https://user-images.githubusercontent.com/8037263/66538047-a5ada680-ead7-11e9-9fc7-187957fb40eb.PNG)

**Comment by blurpesec** [comment]
Thanks Raymond, i've added this to our internal list c:

**Comment by blurpesec** [comment]
This should be fixed now :-)
